# Generated by Django 5.1.7 on 2025-03-13 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=30)),
                ('board_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_management.board')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('contributors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AccountContributor', to='tasks_management.account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_management.account')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_management.project'),
        ),
        migrations.AddField(
            model_name='account',
            name='projects',
            field=models.ManyToManyField(blank=True, to='tasks_management.project'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_created=True)),
                ('task_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('updated_date', models.DateField(auto_now=True)),
                ('column_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_management.column')),
            ],
        ),
    ]
