# Generated by Django 5.1.7 on 2025-03-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='order_position',
        ),
    ]
