# Generated by Django 5.1.7 on 2025-03-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
