# Generated by Django 5.1.7 on 2025-03-12 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_management', '0002_rename_position_column_order_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=70)),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks_management.board')),
            ],
        ),
    ]
