# Generated by Django 5.1.7 on 2025-03-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_management', '0002_remove_board_order_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='order_position',
            field=models.IntegerField(default=1),
        ),
    ]
