# Generated by Django 5.1.7 on 2025-04-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_management', '0004_alter_account_email_alter_projectboard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
