# Generated by Django 5.1.7 on 2025-04-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_management', '0005_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboard',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
