# Generated by Django 5.1.7 on 2025-04-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_management', '0006_projectboard_favorite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectBoard',
            new_name='Project',
        ),
    ]
