# Generated by Django 5.1.7 on 2025-04-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_management', '0008_account_nickname_account_profile_image_account_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
    ]
