# Generated by Django 5.1.7 on 2025-04-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_management', '0010_account_first_login_alter_account_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first_login',
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
