# Generated by Django 5.1.7 on 2025-05-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_management', '0014_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
